---
- name: Install MySQL Server
  remote_user: admin_db
  hosts: mysql-servers
  vars_files:
    - mysql-configs.yaml
  vars:
    ansible_ssh_private_key_file: ./key
  become: true
  roles:
    - geerlingguy.mysql