name: "IaC Checks"

on:
  pull_request:
    branches: 
    - "develop"
    paths:
    - "terraform-iac/**"
    - "ansible-casc/**"
    - ".github/workflows/iac.yml"

  push:
    branches:
    - "develop"
    paths:
    - "terraform-iac/**"
    - "ansible-casc/**"
    - ".github/workflows/iac.yml"

jobs:
  Infrastructure:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set Azure Subscription
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: az account set --subscription $AZURE_SUBSCRIPTION
      
      - name: Terraform init
        working-directory: ./terraform-iac
        run: terraform init
      
      - name: Apply Infra
        working-directory: ./terraform-iac
        env:
          SSH_SHARED_PUB: ${{ secrets.SSH_SHARED_PUB }}
        run: | 
          echo $SSH_SHARED_PUB > key.pub
          terraform apply -auto-approve
     
  Configuration:
    runs-on: self-hosted
    needs: Infrastructure
    steps:
      - uses: actions/checkout@v3
      - name: Run MySQL Install
        working-directory: ./ansible-casc
        env:
          MYSQL_CONFIGS: ${{ secrets.MYSQL_CONFIGS }}
          SSH_SHARED_PRV: ${{ secrets.SSH_SHARED_PRV }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          echo $SSH_SHARED_PRV | base64 -d > key
          chmod 0600 key
          echo $MYSQL_CONFIGS | base64 -d > mysql-configs.yaml
          /home/admin_vm/.local/bin/ansible-galaxy install geerlingguy.mysql
          /home/admin_vm/.local/bin/ansible-playbook -i hosts.ini mysql.yaml
