name: IaC Checks
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Infrastructure:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: ls

      - name: Set Azure Subscription
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: az account set --subscription $AZURE_SUBSCRIPTION
      
      - name: Terraform init
        working-directory: ./terraform-iac
        run: terraform init
      
      - name: Apply Infra
        working-directory: ./terraform-iac
        env:
          SSH_SHARED_PUB: ${{ secrets.SSH_SHARED_PUB }}
        run: | 
          echo $SSH_SHARED_PUB > key.pub
          terraform apply -auto-approve
     
  Configuration:
    runs-on: self-hosted
    needs: Infrastructure
    steps:
      - uses: actions/checkout@v3
      - name: Run MySQL Install
        working-directory: ./ansible-casc
        env:
          MYSQL_CONFIGS: ${{ secrets.MYSQL_CONFIGS }}
          SSH_SHARED_PRV: ${{ secrets.SSH_SHARED_PRV }}
        run: |
          echo $SSH_SHARED_PRV > key
          echo $MYSQL_CONFIGS > mysql-configs.yml
          ansible-galaxy collection install geerlinguy.mysql


