name: "IaC Checks and Deployment"

on:
  workflow_run:
    workflows: ["Coverage and Publish"]
    branches: [main]
    types: [completed]

jobs:
  Infrastructure:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set Azure Subscription
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: az account set --subscription $AZURE_SUBSCRIPTION
      
      - name: Terraform init
        working-directory: ./terraform-iac
        run: terraform init
      
      - name: Apply Infra
        working-directory: ./terraform-iac
        env:
          SSH_SHARED_PUB: ${{ secrets.SSH_SHARED_PUB }}
        run: | 
          echo $SSH_SHARED_PUB > key.pub
          terraform apply -auto-approve
     
  Deployment:
    runs-on: self-hosted
    needs: Infrastructure
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker Build
        working-directory: ./terraform-deployment
        env:
          DOCKER_REGISTRY_GITHUB_TOKEN: ${{ secrets.DOCKER_REGISTRY_GITHUB_TOKEN }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_URL: ${{ secrets.SQL_URL }}
        run: |
          terraform init
          TAG=dev_$(git rev-parse --short "$GITHUB_SHA")
          terraform apply -var="tag=$TAG" \
                          -var="sql_user=$SQL_USER" \
                          -var="sql_password=$SQL_PASSWORD" \
                          -var="sql_url=$SQL_URL" -auto-approve